### ISSUE TITLE
java.io.FileNotFoundException: /proc/tty/drivers: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by ermirshabani1** [arunkumarchauhan/flutter_serial#2]
I get this error when i try to get availablePorts.

**Comment by hs19940808** [comment]
一样的问题，求解决方法

**Comment by arunkumarchauhan** [comment]
Please check for SerialPortFinder.java file and on line number 65  change the file path according to your device requirement where it can find the driver @hs19940808 @ermirshabani1 Or try with chmod permissions code for similar functionality can be found with SerialPort.java
