### ISSUE TITLE
Does not work on Android with USB-Serial adapters

### ISSUE THREAD

**Issue by jnorre** [arunkumarchauhan/flutter_serial#3]
Does not work on Android with FTDI or Prolific USB serial adapters. Other programs like "GCodePrintr" and "Serial USB Terminal" works without any problems with the same adapters.

**Comment by arunkumarchauhan** [comment]
Hello @jnorre ,I had the requirement for Serial USB Terminal and testing device available for the same.So i was not able to test on all types of adapter.You can modify the code according to your requirement,Any PR in this regard will be welcomed.I have used this repository "https://github.com/Andjdd/usbserialport" from github for building this up. I hope this repository can help you too.
